examples:
  - query: "How many terminals are there in Delhi?"
    entities:
      - Facility
      - City
    intent: "count facilities in city"

  - query: "How many terminals are there in Shanghai? List their code in a single line."
    entities:
      - Facility
      - City
    intent: "list facilities in city"

  - query: "How many containers were gated out of Sydney terminal on 10July2025?"
    entities:
      - Container
      - ContainerEvent
      - City
      - Facility
    intent: "count container events at facility"

  - query: "Where is my container HASU1533926 on 20July2025?"
    entities:
      - Container
    intent: "track container location"

  - query: "What is the maximum weight load of a 40 DRY?"
    entities:
      - Container
    intent: "get container specifications"

  - query: "What is the total number of containers gated-in to Rotterdam last week?"
    entities:
      - Container
      - ContainerEvent
      - City
    intent: "count container events in city"

  - query: "What is the height of container HASU1533926?"
    entities:
      - Container
    intent: "container_specification"

  - query: "Show me the details of shipment 256756918?"
    entities:
      - Shipment
    intent: "get shipment details"

  - query: "How many units are linked to booking 250733952?"
    entities:
      - Shipment
      - Container
    intent: "count containers in shipment"

  - query: "Can you tell me how many container units are linked to shipment 256036146 please"
    entities:
      - Shipment
      - Container
    intent: "shipment_container_count"

  - query: "Where is my container HASU1533926"
    entities:
      - Container
    intent: "container_tracking"

  - query: "Can you tell me the current location of container HASU1533926?"
    entities:
      - Container
    intent: "container_tracking"

  - query: "What's the latest movement or location update for container HASU1533926?"
    entities:
      - Container
      - ContainerEvent
    intent: "container_tracking"

  - query: "What is the arrival date for my container GAOU7345026?"
    entities:
      - Container
      - ContainerEvent
    intent: "get container estimated arrival"

  - query: "When can I expect my container GAOU7345026 to arrive?"
    entities:
      - Container
      - ContainerEvent
    intent: "container_eta"

  - query: "What time will my container GAOU7345026 arrive?"
    entities:
      - Container
      - ContainerEvent
    intent: "container_eta"

  - query: "show me the list of container linked to booking 250733952 in a tabular format"
    entities:
      - Shipment
      - Container
    intent: "list containers in shipment"

  - query: "How many containers were gated out of Sydney terminal today?"
    entities:
      - City
      - Facility
      - Container
      - ContainerEvent
    intent: "count container events at facility"

  - query: "What is the number of containers gated-in now in Rotterdam?"
    entities:
      - City
      - Container
      - ContainerEvent
    intent: "count container events in city"

